### ISSUE TITLE
change terminology to conform to draft-ietf-dnsop-terminology-bis

### ISSUE THREAD

**Issue by gmmoura** [gmmoura/draft-moura-dnsop-authoritative-recommendations#1]

**Comment by hardaker** [comment]
Drat.  I thought my edit pass caught most of these. 

[I'm miserable at proper terminology]

**Comment by gmmoura** [comment]
Oh I didn't know you did it. It was just like the first comment that John sent before even we started with the git.
I'll take  a final look into it in any case.

thanks

**Comment by gmmoura** [comment]
done
