### ISSUE TITLE
s/recommendations/other 'softer' word/

### ISSUE THREAD

**Issue by gmmoura** [gmmoura/draft-moura-dnsop-authoritative-recommendations#14]
[Lars-Johan Liman](https://youtu.be/l2ixYuwuaqY?t=1212)  from Netnod: 

 * recommendations may be to strong and unintentionally  lead to a reduction of  diversity of DNS infra -- as more people use the same recommendations.
 * The world 'observations'  was suggested, but IMO that's no strong enough, so we need to compromise here.

**Comment by gmmoura** [comment]
I am thinking of which words suits best, including:

   1. Considerations
   1. Suggestions
   1. Advice
   1. Observations (too weak, not to be used)

Any others?

**Comment by pe-git** [comment]
gmmoura> I am thinking of which words suits best, including:

gmmoura>    1.  Considerations
gmmoura>    2.  Suggestions
gmmoura>    3.  Observations (too weak, not to be used)

I would favor considerations. Suggestions or recommendations seems too
much like endorsement.

**Comment by gmmoura** [comment]
considerations still feels too soft , @hardaker  maybe you have other suggestion?

**Comment by gmmoura** [comment]
OK, let's keep consideration for now. Been through it once again and could not find a better word.
