### ISSUE TITLE
Compare with rfc4786

### ISSUE THREAD

**Issue by gmmoura** [gmmoura/draft-moura-dnsop-authoritative-recommendations#2]
* see rewies-dnsop.md

## [RF:JAb3]

   * src: jabley@hopcount.ca

```
Much of the document is specifically concerned with the implementation of
anycast strategies for DNS, not with authoritative DNS in particular. The advice
would hold for any stateless (or short-duration transaction, where short is
relative to routing stability). One direction the authors might consider taking
this is to update the advice in RFC 4786 with reference to the repeatable
experiments that you cite. Ironically 4786 was criticised for being a document
about DNS that was pretending to be more general; perhaps when welded to your
document the result would be more pleasantly neutral

**Comment by hardaker** [comment]
Hmmm...  I agree with Joe that much of it could be generalized to be more generic.  However, at the same time the recommendations are based on facts that were taken from studies of authoratative.  So maybe the right thing to do is add:

    This document describes recommendations for authoritative DNS zone owners and 
    server operators, as the studies cited in this publication were analyzing authoritative DNS
    zones and services.  It is likely that these recommendations might be useful in a wider
    context, such as for any stateless/short-duration, anycasted service.  Because the
    conclusions of the studies don't verify this fact,  the wording in this document discusses 
    DNS authoratative services only.

Or something better wordsmithed than that?

**Comment by jheidemann** [comment]
On Fri, 30 Nov 2018 13:17:44 -0800, Wes Hardaker wrote: 
>Hmmm... I agree with Joe that much of it could be generalized to be more generic. However, at the
>same time the recommendations are based on facts that were taken from studies of authoratative.
>So maybe the right thing to do is add:
>
>This document describes recommendations for authoritative DNS zone owners and server operators, as the studies cited in this publication were analyzing authoritative DNS zones and services.  It is likely that these recommendations might be useful in a wider context, such as for any stateless/short-duration, anycasted service.  Because the conclusions of the studies don't verify this fact,  the wording in this document discusses DNS authoratative services only.
>
>Or something better wordsmithed than that?
>
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly, view it on GitHub, or mute the thread.
>

Sounds like that could get merged with the last para of the intro that
I wrote to address Paul's comment?
(With the point of the paragraph being: audience definition and scope setting.)

   -John

**Comment by gmmoura** [comment]
Agreed. Merged both of your pars, slashed another one, and now it seems clearer to me.
I'll call it closed (you may reopen if you wish)

/giovane
