### ISSUE TITLE
discuss other routing games (e.g. communities)

### ISSUE THREAD

**Issue by hardaker** [gmmoura/draft-moura-dnsop-authoritative-recommendations#3]
src:  ximaera@gmail.com
Subject: R4

>  -  It can withdraw or pre-prepend its route to some or to all of its
>      neighbors, shrinking its catchment (the number of clients that BGP
>      maps to it), shifting both legitimate and attack traffic to other
>      anycast sites.  The other sites will hopefully have greater
>      capacity and be able to service the queries.

Not necessarily so.
First, one can (may?) use BGP communities to limit the route
announcement propagation, thus making the distribution between sites
more even.
Second, Flowspec/DOTS/selective BH/et cetera.

**Comment by gmmoura** [comment]
I added some text about communities, but now about  Flowspec/DOTS/selective BH and others yet.

**Comment by hardaker** [comment]
I don't think we need to list every particular way in which routing can be shifted, so I changed the text in 56864dc to include "such as" wording in front of the communities discussion.  I think enumeration of the entire list is a document in itself and beyond the scope of this one.  So unless anyone objects, making it generic and listing communities as an example is sufficient to serve as a partial-propagation shift generic solution.

**Comment by hardaker** [comment]
Ok, I put in 76394bb as well to discuss upstream filtering (eg flowspec)

**Comment by gmmoura** [comment]
sounds good to me. thanks Wes

**Comment by mdavids** [comment]
Closed.
