### ISSUE TITLE
Deal with open vs paywall publications

### ISSUE THREAD

**Issue by hardaker** [gmmoura/draft-moura-dnsop-authoritative-recommendations#4]
There is a good discussion happening this week on ietf@ietf.org about citing publications behind a paywall.  It's generally frowned upon to reference (at least normative ones) pay-for-access publications like academic papers at conferences.  I *think* most of these publications we're citing have freely available copies?  Otherwise we should talk about this.

From Heather Flanagan, for example:
In general, I think having an open standard normatively reference
paywalled material is a terrible idea. That said, at the IESG meeting
in Bangkok, we discussed this a bit. Ekr offered an interesting
proposal that would have this kind of reference be treated in a
fashion similar to IPR declarations. I am waiting to see a more
concrete proposal along these lines--and discuss it with the other
streams to see if it can apply to all--before I put anything in a
future style guide.

The larger thread is here:

https://mailarchive.ietf.org/arch/msg/ietf/cQ4K9d_3s65RopPRvefYvI8WRKo

**Comment by gmmoura** [comment]
Thanks Wes. 
So about paywall: only one paper was behind ACM's paywall, so I changed the ref to the author's URL (open).

About the contents and copyright infringement: I think we're good; we pretty much rewriting everything in a non academic style; but please have  a look and see if you're OK with it;  
if you are OK, you may wanna close the issue

/giovane

**Comment by jheidemann** [comment]
On Tue, 11 Dec 2018 23:51:45 -0800, Giovane Moura wrote: 
>Thanks Wes.
>So about paywall: only one paper was behind ACM's paywall, so I changed the ref to the author's URL
>(open).
>
>About the contents and copyright infringement: I think we're good; we pretty much rewriting everything
>in a non academic style; but please have a look and see if you're OK with it;
>if you are OK, you may wanna close the issue

I think one might make the case that most of the academic papers are
informative references and not normative.

They provide background and details, but this RFC is not about protocols
and bit formats.

   -John

**Comment by hardaker** [comment]
John: yes, true.  But you're missing the bigger point that the IETF hates *any* references to paywall documentation.  They will begrudgingly accept some informational references.  I could easily see them pushing back on any recommendation in this draft that linked to a non-accessible document.

That being said, it sounds like we're covered anyway.  Thanks for making the change Giovane!

**Comment by hardaker** [comment]
I'm closing this with @gmmoura's note about we have nothing behind a paywall now.
